name: food_app_ui
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-246.0.dev <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # allows painting and displaying svg files
  flutter_svg: ^1.0.3

  # It provides common validation options
  form_field_validator: ^1.1.0

  # for showing a country code selector
  country_code_picker: ^2.0.2

  # It provides easy access to platform specific location  services
  geolocator: ^8.2.0

  #  It provides easy geocoding and reverse-geocoding features
  geocoding: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/Illustrations/


  # example:
  fonts:
    - family: SF Pro Text
      fonts:
        - asset: assets/font/SF Pro Text/SFProText-Regular.ttf
        - asset: assets/font/SF Pro Text/SFProText-Bold.ttf
          weight: 700
        - asset: assets/font/SF Pro Text/SFProText-Semibold.ttf
          weight: 600
        - asset: assets/font/SF Pro Text/SFProText-Medium.ttf
          weight: 500
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
